#ifndef MOTORCONFIG_H_
#define MOTORCONFIG_H_

#include "../MCAL/DIO.h"

#define MOTOR_EN_1_GPIO		(GPIOD)
#define MOTOR_EN_1_BIT		(BIT4)

#define MOTOR_OUT_1A_GPIO	(GPIOD)
#define MOTOR_OUT_1B_GPIO	(GPIOD)
#define MOTOR_OUT_1A_BIT	(BIT6)
#define MOTOR_OUT_1B_BIT	(BIT7)


#define MOTOR_EN_2_GPIO		(GPIOD)
#define MOTOR_EN_2_BIT		(BIT5)

#define MOTOR_OUT_2A_GPIO	(GPIOD)
#define MOTOR_OUT_2B_GPIO	(GPIOD)
#define MOTOR_OUT_2A_BIT	(BIT2)
#define MOTOR_OUT_2B_BIT	(BIT3)

#endif /* MOTORDC_CFG_H_ */
